[theme]
base                  = "light"
primaryColor          = "#023739"
backgroundColor       = "#F5F7FA"
secondaryBackgroundColor = "#FFFFFF"
textColor             = "#1A202C"
font                  = "sans serif"
